spring:
  application:
    name: newshub-ingestor

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: ${PORT:8081}

newshub:
  api:
    base-url: ${API_BASE_URL:http://localhost:8080}
  kafka:
    topics:
      news: ${NEWS_TOPIC:newshub.news}
  refresh:
    schedule:
      enabled: ${REFRESH_SCHEDULE_ENABLED:false}
      fixed-delay-seconds: ${REFRESH_SCHEDULE_DELAY:300}
