spring:
  application:
    name: newshub-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/newshub}
    username: ${DB_USER:newshub}
    password: ${DB_PASS:newshub}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: ${newshub.kafka.consumer-group:newshub-api}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.example.newshub.common.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: ${PORT:8080}

newshub:
  kafka:
    topics:
      news: ${NEWS_TOPIC:newshub.news}
  ingestor:
    base-url: ${INGESTOR_URL:http://localhost:8081}
